baseurl: https://fgksgf.github.io
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Hoshea's Blog

languages:
    en:
        languageName: English
        title: Hoshea's Blog
        weight: 1

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics: UA-118341733-1

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

hasCJKLanguage: true

permalinks:
    post: /p/:slug/
    page: /:slug/

enableEmoji: true
enableInlineShortcodes: true

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: img/favicon.ico

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006

    sidebar:
        subtitle: Do something today that your future self will thank you for.
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-ND 4.0

    comments:
        enabled: true
        provider: utterances
        utterances:
            repo: fgksgf/blog-comment-system
            issueTerm: pathname
            theme: preferred-color-scheme

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

        archives:
            limit: 5
            path: archives

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true
        
        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
            icon: home

        - identifier: about
          name: About
          url: about
          weight: -90
          params: 
            icon: user

        - identifier: archives
          name: Archives
          url: archives
          weight: -90
          params:
            icon: archives

        - identifier: search
          name: Search
          url: search
          weight: -90
          params:
            icon: search

    # social:
    #     - identifier: github
    #       name: GitHub
    #       url: https://github.com/fgksgf
    #       params:
    #           icon: brand-github

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: false
        lineNumbersInTable: true
        tabWidth: 4
